# Generated by Django 4.0.1 on 2022-07-03 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('take_a_break_app', '0001_initial'), ('take_a_break_app', '0002_user_web_rename_website_websites'), ('take_a_break_app', '0003_alter_user_web_user_alter_user_web_websites'), ('take_a_break_app', '0004_alter_user_web_websites')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='websites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_a_break_app.user')),
                ('websites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_a_break_app.websites')),
            ],
        ),
    ]
