# Generated by Django 4.0.1 on 2022-07-03 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('take_a_break_app', '0001_squashed_0004_alter_user_web_websites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_web',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_webs', to='take_a_break_app.user'),
        ),
    ]
