# Generated by Django 4.0.1 on 2022-07-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_a_break_app', '0003_alter_user_web_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_web',
            name='websites',
        ),
        migrations.AddField(
            model_name='user_web',
            name='websites',
            field=models.ManyToManyField(to='take_a_break_app.websites'),
        ),
    ]
