# Generated by Django 4.0.1 on 2022-08-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_a_break_app', '0006_alter_user_web_websites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websites',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='websites',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
